# Generated by Django 3.2.9 on 2022-07-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('faculty', models.CharField(choices=[('Physical Sciences', 'Physical Sciences'), ('Bio Sciences', 'Bio Sciences')], max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_book', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('file', models.FileField(upload_to='')),
                ('file_type', models.CharField(choices=[('Texts Books', 'Texts Books'), ('Past Questions', 'Past Questions'), ('Hand Outs', 'Hand Outs')], max_length=20)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=20)),
                ('year', models.CharField(choices=[('Year-1', 'Year-1'), ('Year-2', 'Year-2'), ('Year-3', 'Year-3'), ('Year-4', 'Year-4')], max_length=20)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BookCategories',
            },
        ),
    ]
