# Generated by Django 3.2.9 on 2022-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='about_book',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
