# Generated by Django 3.2.9 on 2022-07-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_bookcategory_about_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
