# Generated by Django 3.2.9 on 2022-08-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220810_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='School',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_name',
            new_name='school_name',
        ),
    ]
