# Generated by Django 3.2.9 on 2022-07-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_bookcategory_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department'),
        ),
    ]
