# Generated by Django 3.2.9 on 2022-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
