# Generated by Django 3.2.9 on 2022-08-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20220810_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='product_image',
            new_name='product_cover_image',
        ),
        migrations.CreateModel(
            name='AdvertImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.advert')),
            ],
        ),
    ]
